jobs:
  update_labels:
    runs-on: ubuntu-latest
    steps:
      # When PR is opened, set to "pending review".
      - name: Initial Label
        if: github.event.action == 'opened'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'pending review'

      # If reviewer asks for changes, swap to "needs revision".
      - name: Remove Pending Review (Needs Revision)
        if: github.event.review.state == 'changes_requested'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 'pending review'
  
      - name: Add Needs Revision Label
        if: github.event.review.state == 'changes_requested'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'needs revision'

      # If reviewer approves, swap to "accepted"
      - name: Remove Pending Review (Accepted)
        if: github.event.review.state == 'approved'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 'pending review'
  
      - name: Add Accepted Label
        if: github.event.review.state == 'approved'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'accepted'